global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "simple-service"
    static_configs:
      - targets: ["host.docker.internal:9092"]

  - job_name: "gin-service"
    static_configs:
      - targets: ["host.docker.internal:9093"]

  - job_name: "grpc-service"
    static_configs:
      - targets: ["host.docker.internal:9094"]
